services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: football_backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./host_media:/app/media:rw
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
    command: >
      sh -c "
        pip install -r requirements.txt &&
        python manage.py migrate --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: football_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
      API_URL: "http://backend:8000"
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      NEXT_TURBOPACK_WATCHER_MODE: "poll"
    command: >
      sh -c "
        npm install &&
        npm run dev
      "
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      - backend

  adminer:
    image: adminer:latest
    container_name: football_adminer
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"