# Generated by Django 5.2.13 on 2026-04-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=255, verbose_name='Название позиции')),
                ('position_short_name', models.CharField(max_length=5, verbose_name='Название позиции(кратко)')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год команды')),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Года',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя игока')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия Игрока')),
                ('birth', models.DateField(verbose_name='Дата рождения игрока')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teams/players/', verbose_name='Фото игрока')),
                ('position', models.ManyToManyField(blank=True, to='teams.position')),
                ('year', models.ManyToManyField(to='teams.year')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
    ]
