# Generated by Django 5.2.13 on 2026-04-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ManyToManyField(blank=True, to='teams.position', verbose_name='Позиция игрока'),
        ),
        migrations.AlterField(
            model_name='player',
            name='year',
            field=models.ManyToManyField(to='teams.year', verbose_name='Год игрока'),
        ),
    ]
