# Generated by Django 5.2.13 on 2026-04-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок поста')),
                ('text', models.TextField(verbose_name='Текст поста')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория поста')),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Изображение поста')),
                ('is_published', models.BooleanField(default=False, verbose_name='Показывать пост')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at'],
            },
        ),
    ]
